spring:
  application:
    name: reservation
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

payment:
  failure-rate: 20
